on: '3'
services:
    app:
        image: mc2labs/nodejs:dev-alpine
        ports:
            - "80:80"
        volumes:
            - ".:/app"
        environment:
            HOST: "0.0.0.0"
            PORT: "80"

